[package]
name = "math-rs"
version = "0.1.0"
authors = ["xiangminli <xiangminli@alumni.sjtu.edu.cn>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "math"

[dependencies]
lazy_static = "1.4.0"
