name: test

on:
  push:
    branches-ignore:
    - main
  pull_request:
    branches: [ 'main' ]

jobs:
  test:
    runs-on: ubuntu-latest
    container: 
      image: rust:1.63.0-bullseye

    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false
    - name: Rust toolchains
      run: |
        rustc --version &&
        rustup --version &&
        cargo --version
      shell: bash
    - name: Cache cargo registry
      uses: actions/cache@v3
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.toml') }}
    - name: Cache cargo index
      uses: actions/cache@v3
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.toml') }}
    - name: Run tests
      run: cargo test
      shell: bash
